## 16. tf data api from TF tutorial

- https://www.tensorflow.org/guide/data

In [6]:
import os
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as sp
import datetime
import warnings; warnings.filterwarnings('ignore')
plt.style.use('ggplot')
%matplotlib inline

# Options for pandas
pd.options.display.max_columns = 150

In [7]:
import tensorflow as tf
import tensorflow.keras as keras # 케라스 쓸때 반드시 이것 추가... 주의https://stackoverflow.com/questions/72409779/modulenotfounderror-no-module-named-tensorflow-keras-i-tried-almost-everyth

In [8]:
import pathlib

### Basic mechanics

In [9]:
dataset = tf.data.Dataset.from_tensor_slices([8, 3, 0, 8, 2, 1])
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [10]:
for elem in dataset:
    print(elem)

tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [11]:
it = iter(dataset)
print(next(it))

tf.Tensor(8, shape=(), dtype=int32)


In [13]:
it = iter(dataset)
print(next(it).numpy())

8


In [14]:
tf.random.uniform([4, 10])

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[0.7894871 , 0.37685347, 0.49148118, 0.08717918, 0.5787082 ,
        0.25610447, 0.9556042 , 0.9303055 , 0.24314928, 0.84145963],
       [0.44826484, 0.85743   , 0.5415789 , 0.8423587 , 0.11443353,
        0.03812206, 0.14010274, 0.7827902 , 0.7173928 , 0.02436388],
       [0.08922732, 0.35386074, 0.5491632 , 0.40145957, 0.49850845,
        0.39804852, 0.58155715, 0.6659974 , 0.9792994 , 0.579414  ],
       [0.09282649, 0.3197416 , 0.7566869 , 0.14619303, 0.19021559,
        0.40835202, 0.20252836, 0.73521197, 0.05922711, 0.5176002 ]],
      dtype=float32)>

In [16]:
dataset1 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([4, 10]))

In [17]:
dataset1

<TensorSliceDataset shapes: (10,), types: tf.float32>

In [19]:
dataset1.element_spec # 내부 요소의 타입을 확인할 때

TensorSpec(shape=(10,), dtype=tf.float32, name=None)

In [20]:
dataset2 = tf.data.Dataset.from_tensor_slices(
   (tf.random.uniform([4]),
    tf.random.uniform([4, 100], maxval=100, dtype=tf.int32)))

In [21]:
dataset2

<TensorSliceDataset shapes: ((), (100,)), types: (tf.float32, tf.int32)>

In [22]:
dataset2.element_spec

(TensorSpec(shape=(), dtype=tf.float32, name=None),
 TensorSpec(shape=(100,), dtype=tf.int32, name=None))

In [23]:
dataset3 = tf.data.Dataset.zip((dataset1, dataset2))
dataset3.element_spec

(TensorSpec(shape=(10,), dtype=tf.float32, name=None),
 (TensorSpec(shape=(), dtype=tf.float32, name=None),
  TensorSpec(shape=(100,), dtype=tf.int32, name=None)))

In [24]:
dataset1 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([4, 10], minval=1, maxval=10, dtype=tf.int32))
dataset1

<TensorSliceDataset shapes: (10,), types: tf.int32>

In [25]:
for z in dataset1:
    print(z.numpy())

[9 5 3 6 8 4 1 4 9 3]
[6 6 3 5 6 3 8 3 1 1]
[3 1 8 5 9 5 2 9 3 2]
[7 9 2 6 4 8 3 8 1 7]


In [26]:
dataset2 = tf.data.Dataset.from_tensor_slices((tf.random.uniform([4]),
    tf.random.uniform([4, 100], maxval=100, dtype=tf.int32)))
dataset2

<TensorSliceDataset shapes: ((), (100,)), types: (tf.float32, tf.int32)>

In [28]:
for z in dataset2:
    print(z)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.7790923>, <tf.Tensor: shape=(100,), dtype=int32, numpy=
array([78, 23, 44, 49, 30,  6, 77, 84, 31,  0, 48, 59, 88, 41, 65, 58, 71,
       31, 63, 39,  9, 91,  1, 47,  4, 72, 99, 95, 56, 14, 61, 78, 11, 16,
       71,  7, 10, 12, 60, 98, 92, 86,  7, 85, 58,  1, 54, 61, 62,  1, 17,
        3, 23, 19, 44, 31, 48, 57, 43, 80, 45, 98, 31, 48, 65, 31, 70, 32,
        7,  3, 14, 21, 46, 52, 40, 22, 86, 69, 40, 97, 59, 78, 91, 42, 74,
        7, 30, 57,  8, 62, 97, 69, 72, 45, 11, 71,  2,  7, 24, 27])>)
(<tf.Tensor: shape=(), dtype=float32, numpy=0.29318023>, <tf.Tensor: shape=(100,), dtype=int32, numpy=
array([94, 60, 45, 19, 17, 41, 20, 10,  3, 32, 79, 77, 44, 53,  7, 98, 11,
       39, 66, 18, 71, 21, 47, 13, 87,  6, 83, 44, 40, 63, 33, 75, 99, 66,
       75, 43, 68, 14, 80, 27, 29, 72, 89, 98,  3, 20, 28, 32, 97, 41,  3,
       12, 93,  0,  4, 19, 16, 31, 84, 94, 68, 30, 49, 80, 22, 20, 17, 16,
       17, 35, 11,  7, 35, 79, 90, 49, 71, 18, 76,

In [29]:
dataset3 = tf.data.Dataset.zip((dataset1, dataset2))
dataset3

<ZipDataset shapes: ((10,), ((), (100,))), types: (tf.int32, (tf.float32, tf.int32))>

In [30]:
for a, (b, c) in dataset3:
    print('shapes: {a.shape}, {b.shape}, {c.shape}'.format(a=a, b=b, c=c))

shapes: (10,), (), (100,)
shapes: (10,), (), (100,)
shapes: (10,), (), (100,)
shapes: (10,), (), (100,)


### Reading input data

In [31]:
train, test = tf.keras.datasets.fashion_mnist.load_data()

In [32]:
train

(array([[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        ...,
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],

In [33]:
images, labels = train
images = images /255

In [34]:
dataset = tf.data.Dataset.from_tensor_slices((images, labels))
dataset

<TensorSliceDataset shapes: ((28, 28), ()), types: (tf.float64, tf.uint8)>

In [35]:
dataset.element_spec

(TensorSpec(shape=(28, 28), dtype=tf.float64, name=None),
 TensorSpec(shape=(), dtype=tf.uint8, name=None))

In [36]:
len(dataset)

60000

### CSV 데이터 다루기

In [37]:
titanic_file = tf.keras.utils.get_file("train.csv", "https://storage.googleapis.com/tf-datasets/titanic/train.csv")

32768/30874 [===============================] - 0s 0us/step


In [38]:
titanic_file

'C:\\Users\\Main\\.keras\\datasets\\train.csv'

In [39]:
df = pd.read_csv(titanic_file)

In [40]:
df.head()

survived     sex   age  n_siblings_spouses  parch     fare  class     deck  \
0         0    male  22.0                   1      0   7.2500  Third  unknown   
1         1  female  38.0                   1      0  71.2833  First        C   
2         1  female  26.0                   0      0   7.9250  Third  unknown   
3         1  female  35.0                   1      0  53.1000  First        C   
4         0    male  28.0                   0      0   8.4583  Third  unknown   

   embark_town alone  
0  Southampton     n  
1    Cherbourg     n  
2  Southampton     y  
3  Southampton     n  
4   Queenstown     y

In [42]:
titanic = tf.data.Dataset.from_tensor_slices(dict(df))

In [43]:
titanic

<TensorSliceDataset shapes: {survived: (), sex: (), age: (), n_siblings_spouses: (), parch: (), fare: (), class: (), deck: (), embark_town: (), alone: ()}, types: {survived: tf.int64, sex: tf.string, age: tf.float64, n_siblings_spouses: tf.int64, parch: tf.int64, fare: tf.float64, class: tf.string, deck: tf.string, embark_town: tf.string, alone: tf.string}>

In [44]:
titanic.element_spec

{'survived': TensorSpec(shape=(), dtype=tf.int64, name=None),
 'sex': TensorSpec(shape=(), dtype=tf.string, name=None),
 'age': TensorSpec(shape=(), dtype=tf.float64, name=None),
 'n_siblings_spouses': TensorSpec(shape=(), dtype=tf.int64, name=None),
 'parch': TensorSpec(shape=(), dtype=tf.int64, name=None),
 'fare': TensorSpec(shape=(), dtype=tf.float64, name=None),
 'class': TensorSpec(shape=(), dtype=tf.string, name=None),
 'deck': TensorSpec(shape=(), dtype=tf.string, name=None),
 'embark_town': TensorSpec(shape=(), dtype=tf.string, name=None),
 'alone': TensorSpec(shape=(), dtype=tf.string, name=None)}

In [46]:
for feature_batch in titanic.take(1):
    for key, value in feature_batch.items():
        print("  {!r:20s}: {}".format(key, value))

  'survived'          : 0
  'sex'               : b'male'
  'age'               : 22.0
  'n_siblings_spouses': 1
  'parch'             : 0
  'fare'              : 7.25
  'class'             : b'Third'
  'deck'              : b'unknown'
  'embark_town'       : b'Southampton'
  'alone'             : b'n'


`tf.data.experimental.make_csv_dataset` 함수를 사용하면 csv 포맷 파일의 정보를 편하게 요약할 수 있다.

In [48]:
titanic_batches = tf.data.experimental.make_csv_dataset(titanic_file, batch_size = 4,
                                                       label_name = 'survived') # 파일경로로 직접 읽음

In [49]:
titanic_batches

<PrefetchDataset shapes: (OrderedDict([(sex, (4,)), (age, (4,)), (n_siblings_spouses, (4,)), (parch, (4,)), (fare, (4,)), (class, (4,)), (deck, (4,)), (embark_town, (4,)), (alone, (4,))]), (4,)), types: (OrderedDict([(sex, tf.string), (age, tf.float32), (n_siblings_spouses, tf.int32), (parch, tf.int32), (fare, tf.float32), (class, tf.string), (deck, tf.string), (embark_town, tf.string), (alone, tf.string)]), tf.int32)>

In [50]:
titanic_batches.element_spec

(OrderedDict([('sex', TensorSpec(shape=(4,), dtype=tf.string, name=None)),
              ('age', TensorSpec(shape=(4,), dtype=tf.float32, name=None)),
              ('n_siblings_spouses',
               TensorSpec(shape=(4,), dtype=tf.int32, name=None)),
              ('parch', TensorSpec(shape=(4,), dtype=tf.int32, name=None)),
              ('fare', TensorSpec(shape=(4,), dtype=tf.float32, name=None)),
              ('class', TensorSpec(shape=(4,), dtype=tf.string, name=None)),
              ('deck', TensorSpec(shape=(4,), dtype=tf.string, name=None)),
              ('embark_town',
               TensorSpec(shape=(4,), dtype=tf.string, name=None)),
              ('alone', TensorSpec(shape=(4,), dtype=tf.string, name=None))]),
 TensorSpec(shape=(4,), dtype=tf.int32, name=None))

In [51]:
for feature_batch, label_batch in titanic_batches.take(1):
    print("'survived': {}".format(label_batch))
    print("features:")
    for key, value in feature_batch.items():
        print("  {!r:20s}: {}".format(key, value))

'survived': [0 0 1 0]
features:
  'sex'               : [b'male' b'male' b'female' b'male']
  'age'               : [28. 29. 33. 25.]
  'n_siblings_spouses': [8 0 1 1]
  'parch'             : [2 0 0 0]
  'fare'              : [69.55 30.   53.1  26.  ]
  'class'             : [b'Third' b'First' b'First' b'Second']
  'deck'              : [b'unknown' b'D' b'E' b'unknown']
  'embark_town'       : [b'Southampton' b'Southampton' b'Southampton' b'Southampton']
  'alone'             : [b'n' b'y' b'n' b'n']


일부 컬럼만 가져오기

In [52]:
titanic_batches = tf.data.experimental.make_csv_dataset(
    titanic_file, batch_size=4,
    label_name="survived", select_columns=['class', 'fare', 'survived'])

In [53]:
for feature_batch, label_batch in titanic_batches.take(1):
    print("'survived': {}".format(label_batch))
    for key, value in feature_batch.items():
        print("  {!r:20s}: {}".format(key, value))

'survived': [1 0 0 1]
  'fare'              : [ 7.7333 15.2458  8.4333 26.    ]
  'class'             : [b'Third' b'Third' b'Third' b'Second']


### Batching dtaset elements

simple batching

In [54]:
inc_dataset = tf.data.Dataset.range(100)
dec_dataset = tf.data.Dataset.range(0, -100, -1)
dataset = tf.data.Dataset.zip((inc_dataset, dec_dataset))
batched_dataset = dataset.batch(4)

In [55]:
batched_dataset # None으로 나오는 이유 배치로 잡다보니 나머지 때문에.. Drop remainder 쓰면 배치 사이즈 보임

<BatchDataset shapes: ((None,), (None,)), types: (tf.int64, tf.int64)>

In [56]:
batched_dataset.element_spec

(TensorSpec(shape=(None,), dtype=tf.int64, name=None),
 TensorSpec(shape=(None,), dtype=tf.int64, name=None))

In [58]:
for batch in batched_dataset.take(4):
    print([arr.numpy() for arr in batch])

[array([0, 1, 2, 3], dtype=int64), array([ 0, -1, -2, -3], dtype=int64)]
[array([4, 5, 6, 7], dtype=int64), array([-4, -5, -6, -7], dtype=int64)]
[array([ 8,  9, 10, 11], dtype=int64), array([ -8,  -9, -10, -11], dtype=int64)]
[array([12, 13, 14, 15], dtype=int64), array([-12, -13, -14, -15], dtype=int64)]


In [59]:
dataset = dataset.batch(7, drop_remainder=True)

In [60]:
dataset

<BatchDataset shapes: ((7,), (7,)), types: (tf.int64, tf.int64)>

In [61]:
dataset.element_spec

(TensorSpec(shape=(7,), dtype=tf.int64, name=None),
 TensorSpec(shape=(7,), dtype=tf.int64, name=None))

Batching tensors with padding

In [62]:
dataset = tf.data.Dataset.range(100)
dataset = dataset.map(lambda x: tf.fill([tf.cast(x, tf.int32)], x))
dataset = dataset.padded_batch(4, padded_shapes=(None,))

for batch in dataset.take(2):
    print(batch.numpy())
    print()

[[0 0 0]
 [1 0 0]
 [2 2 0]
 [3 3 3]]

[[4 4 4 4 0 0 0]
 [5 5 5 5 5 0 0]
 [6 6 6 6 6 6 0]
 [7 7 7 7 7 7 7]]



### Training workflows

Processing multiple epochs

In [64]:
titanic_file = tf.keras.utils.get_file("train.csv", "https://storage.googleapis.com/tf-datasets/titanic/train.csv")
titanic_lines = tf.data.TextLineDataset(titanic_file)

In [65]:
titanic_lines

<TextLineDatasetV2 shapes: (), types: tf.string>

In [66]:
for line in titanic_lines.take(10):
  print(line.numpy())

b'survived,sex,age,n_siblings_spouses,parch,fare,class,deck,embark_town,alone'
b'0,male,22.0,1,0,7.25,Third,unknown,Southampton,n'
b'1,female,38.0,1,0,71.2833,First,C,Cherbourg,n'
b'1,female,26.0,0,0,7.925,Third,unknown,Southampton,y'
b'1,female,35.0,1,0,53.1,First,C,Southampton,n'
b'0,male,28.0,0,0,8.4583,Third,unknown,Queenstown,y'
b'0,male,2.0,3,1,21.075,Third,unknown,Southampton,n'
b'1,female,27.0,0,2,11.1333,Third,unknown,Southampton,n'
b'1,female,14.0,1,0,30.0708,Second,unknown,Cherbourg,n'
b'1,female,4.0,1,1,16.7,Third,G,Southampton,n'


tf.data는 한 데이터셋으로 multiple epoch를 반복하는 두가지 방법이 있다.

1) 가장 간단한 방법은 repeat함수를 사용하는 방법이다.